-- Org-chart template SUBCATEGORIES (run after supabase_org_chart_templates.sql)
-- Subcategories belong to a category; templates may be filed under one.

create table if not exists public.org_chart_template_subcategories (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category_id bigint references public.org_chart_template_categories(id) on delete cascade,
  created_by  uuid,
  created_at  timestamptz not null default now()
);

create index if not exists org_chart_template_subcategories_category_idx
  on public.org_chart_template_subcategories (category_id);

-- Templates can reference a subcategory (optional).
alter table public.org_chart_templates
  add column if not exists subcategory_id bigint
  references public.org_chart_template_subcategories(id) on delete set null;

-- RLS — same permissive authenticated policy as the rest of the app.
alter table public.org_chart_template_subcategories enable row level security;
drop policy if exists "auth all" on public.org_chart_template_subcategories;
create policy "auth all" on public.org_chart_template_subcategories
  for all to authenticated using (true) with check (true);
