-- Stores each Org Chart Wizard run so Sam can learn (in-context) from the
-- difference between what it drafted and what the user accepted. On future
-- runs the most recent accepted structures are fed back as few-shot examples.

create table if not exists public.org_chart_wizard_feedback (
  id          bigint generated by default as identity primary key,
  description text,                 -- the company description the user gave
  draft       jsonb,                -- what Sam proposed: { topTitle, divisions:[...] }
  final       jsonb,                -- what the user accepted: { topTitle, divisions:[...] }
  created_by  uuid,
  created_at  timestamptz not null default now()
);

create index if not exists org_chart_wizard_feedback_created_idx
  on public.org_chart_wizard_feedback (created_at desc);

alter table public.org_chart_wizard_feedback enable row level security;
drop policy if exists "auth all" on public.org_chart_wizard_feedback;
create policy "auth all" on public.org_chart_wizard_feedback
  for all to authenticated using (true) with check (true);
