-- Org-chart template library
-- Run this in the Supabase SQL editor for project jjlnpywpmoukgwmwczbz.

-- 1) Categories templates are grouped by.
create table if not exists public.org_chart_template_categories (
  id          bigint generated by default as identity primary key,
  name        text not null,
  created_by  uuid,
  created_at  timestamptz not null default now()
);

-- 2) The templates themselves. `data` is a JSON snapshot of the chart's
--    nodes + edges (employees removed; positions stored by title).
create table if not exists public.org_chart_templates (
  id          bigint generated by default as identity primary key,
  name        text not null,
  category_id bigint references public.org_chart_template_categories(id) on delete set null,
  data        jsonb not null default '{}'::jsonb,
  created_by  uuid,
  created_at  timestamptz not null default now()
);

create index if not exists org_chart_templates_category_idx
  on public.org_chart_templates (category_id);

-- 3) RLS — match the rest of the app: any authenticated user can read/write.
alter table public.org_chart_template_categories enable row level security;
alter table public.org_chart_templates           enable row level security;

drop policy if exists "auth all" on public.org_chart_template_categories;
create policy "auth all" on public.org_chart_template_categories
  for all to authenticated using (true) with check (true);

drop policy if exists "auth all" on public.org_chart_templates;
create policy "auth all" on public.org_chart_templates
  for all to authenticated using (true) with check (true);
